default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

  <<: *default
  database: health_app_cache_production

queue:
  <<: *default
  database: health_app_queue_production

cable:
  <<: *default
  database: health_app_cable_production

development:
  <<: *default
  database: health_app_development

test:
  <<: *default
  database: health_app_test

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

cache_production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

queue_production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

cable_production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

# Aliases for production multi-db
cache:
  <<: *cache_production
queue:
  <<: *queue_production
cable:
  <<: *cable_production
