
production: &production
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

cache:
  <<: *production
queue:
  <<: *production
cable:
  <<: *production

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: health_development

test:
  <<: *default
  database: health_test
